[package]
name = "atcoder_gray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
libm = "=0.2.1"
num = "0.4.0"
proconio = {version = "0.4.3", features = ["derive"]}
